---

- hosts: webserver
  become: true
  tasks:

   - name: install apache2 and php support for Ubuntu
    tags: test
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  tasks:

  - name: create simone user
    tags: always
    user:
      name: simone
      groups: root

  - name: add ssh for simone
    authorized_key:
      user: simone
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPobBtCk0yZ0t7G1RhdjXhYjmaIRcU4cbpHRiphKAmVI ansible"


  - name: add sudoer file for simone
    copy:
      src: sudoer_simone
      dest: /etc/sudoers.d/simone
      owner: root
      group: root
      mode: 0440
