---

- hosts: webserver
  become: true
  tasks:

  - name: install apache2 and php support for Ubuntu
    tags: test
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: webserver
  become: true
  tasks:

  - name: install mariadb for Ubuntu
    tags: test2
    apt:
      name: mariadb-server
      state: latest
