---

- hosts: webserver
  become: true
  tasks:

  - name: install apache2 and php support for Ubuntu
    tags: test
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: copy default hmtl2 file
    copy: 
      src: default_site.html 
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: '0644'

- hosts: webserver
  become: true
  tasks:

  - name: install mariadb for Ubuntu
    tags: test2
    apt:
      name: mariadb-server
      state: latest
